# This is the main configuration for the plugin
# debug value can be true or false. When debug is true, the application prints more in detail log messages
debug: false
# Version number of the application do not change this
version: 2.0S

enabled-worlds:
  - world1
  - world2

messages:
  prefix: "&7[&6VTE&7] &r"
  noPermission: "&cYou do not have permission to do this"
  configReloaded: "&aConfig reloaded"
  disabledWorld: "&cThis world is disabled"