name: VillagerTradeEdit
version: '${version}'
main: org.yusaki.villagertradeedit.VillagerTradeEdit
api-version: '1.20'
author: Yusaki
description: Lets you edit villager trades.
folia-supported: true

permissions:
  villagertradeedit.open:
    description: Allows opening of the villager trade editor
    default: op
